### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by erikv85** [Upekshe/simple-ldap-server#4]
Hi, how do you actually use this? I have the server up and running on docker ("LDAP server up at: ldap://0.0.0.0:389"), but how do I query or configure it? Please add documentation.

**Comment by Upekshe** [comment]
You connect to the given address like you connect to any other LDAP server, and perform user bind operations and search operations. But, yes I'll a separate section to the documentation with info how to test this with a standard tool like `ldapsearch`

**Comment by Upekshe** [comment]
Included a how to use section to the readme. Hope that section is clear enough
